### ISSUE TITLE
Develop profile/account page.

### ISSUE THREAD

**Issue by vovsike** [Prisposoba/back-end#2]
We need to develop the logic behind account page. This might be one of the most visited page on the website, therefore it should be carefully planned and developed for comfortable interactions with user.

This only includes basic functionality as the project spec continues to increase. 

- Adding extra information such as name and surname or passport number (Verification) only for investors
- Changing password and email
- Profile customisation
- Add badges and maybe some sort of "showoff"

GDPR complained. Consent to process personal information.

Personal information to be collected:
Email, nickname, telephone.

**Comment by Iv-Alex** [comment]
![image](https://user-images.githubusercontent.com/75684216/107672419-ead28180-6ca5-11eb-91f5-dba14f99fe33.png)

**Comment by vovsike** [comment]
![image](https://user-images.githubusercontent.com/57632637/109155972-2c643180-7768-11eb-9573-fb6a7d6e2d8d.png)
This is a first iteration of functionality for account page
